# Generated by Django 4.1.4 on 2023-03-13 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usermodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('services', models.CharField(choices=[('electrician', 'ELECTRICIAN'), ('plumber', 'PLUMBER'), ('cleaner', 'CLEANER'), ('painter', 'PAINTER'), ('carpenter', 'CARPENTER'), ('welder', 'WELDER')], max_length=50)),
                ('serviceTime', models.DateTimeField()),
                ('serviceDate', models.DateField()),
                ('state', models.CharField(max_length=20)),
                ('pincode', models.IntegerField()),
            ],
        ),
    ]
